#开发环境

server:
  port: 18007
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain

spring:
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://databases.ptcc9.top:3306/c_xxx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: c_xxx
    password: 123456
    hikari:
      minimum-idle: 2
      idle-timeout: 180000
      maximum-pool-size: 5
      auto-commit: true
      pool-name: SosHikari
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 文件上传配置
file:
  upload:
      path: D:\uploads\  # 文件上传根路径（Windows系统）
#    path: /home/program/jiankangyinshi/uploads/  # 文件上传根路径（Windows系统）
      url-prefix: http://localhost:18007/uploads/  # 文件访问URL前缀
#    url-prefix: http://47.97.154.151:18003/uploads/  # 文件访问URL前缀